title: "DBを利用せずLINE✕StripeでECアプリを作ってみよう！"
summary: "DBを利用せずStripeの情報を軸に、LINE ECボットを作る本です。"
topics: ["line", "stripe", "ec", "bot"]
published: false
price: 5000
chapters:
  - introduction
  - process
  - environment
  - rich-menu
  - stripe_init
  - stripe_product_list
  - stripe_payment_onetime
  - stripe_payment_regular
  - stripe_order
